eatables/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, include

from menu.views import loggedin, not_authorized, loggedout
from menu import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    url(r'^accounts/loggedin/$', loggedin, name='loggedin'),
    url(r'^accounts/not_authorized/$', not_authorized, name='not_authorized'),
    url(r'^loggedout/$', loggedout, name='loggedout'),

    # default view
    url(r'^$', views.index, name='my_recipes'),

    # all recipes
    url(r'^clear_recipe_filter/$', views.clear_recipe_filter, name='clear_recipe_filter'),
    url(r'^discover/$', views.discover, name='discover'),

    # recipe
    url(r'^(?P<recipe_id>[0-9]+)/recipe_details/$', views.recipe_details, name='recipe_details'),
    url(r'^add_recipe/$', views.add_recipe, name='add_recipe'),
    url(r'^(?P<recipe_id>[0-9]+)/edit_recipe/$', views.edit_recipe, name='edit_recipe'),
    url(r'^(?P<recipe_id>[0-9]+)/delete_recipe_forever/$', views.delete_recipe_forever, name='delete_recipe_forever'),
    url(r'^add_tag/$', views.add_tag, name='add_tag'),

    # ingredients
    url(r'^add_ingredient_to_recipe/$', views.add_ingredient_to_recipe, name='add_ingredient_to_recipe'),
    url(r'^(?P<ingredient_id>[0-9]+)/edit_ingredient/$', views.edit_ingredient, name='edit_ingredient'),
    url(r'^(?P<ingredient_id>[0-9]+)/delete_ingredient/$', views.delete_ingredient, name='delete_ingredient'),
    url(r'^(?P<ingredient_id>[0-9]+)/move_ingredient_up/$', views.move_ingredient_up, name='move_ingredient_up'),
    url(r'^(?P<ingredient_id>[0-9]+)/move_ingredient_down/$', views.move_ingredient_down, name='move_ingredient_down'),

    # shopping list
    url(r'^add_to_shopping_list/$', views.add_to_shopping_list, name='add_to_shopping_list'),
    url(r'^shopping_list/$', views.shopping_list, name='shopping_list'),
    url(r'^(?P<shopping_list_id>[0-9]+)/shopping_list_check_off/$', views.shopping_list_check_off, name='shopping_list_check_off'),
    url(r'^(?P<shopping_list_id>[0-9]+)/shopping_list_delete/$', views.shopping_list_delete, name='shopping_list_delete'),

    # comments
    url(r'^add_comment_to_recipe/$', views.add_comment_to_recipe, name='add_comment_to_recipe'),
    url(r'^(?P<comment_id>[0-9]+)/comment_delete/$', views.comment_delete, name='comment_delete'),

]

menu/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.contrib.auth.models import User

from menu.choices import *


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Recipe(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80, unique=True)
    cook_method = models.IntegerField(choices=COOK_METHOD_CHOICES, default=0)
    temperature = models.CharField(max_length=10, null=True, blank=True)
    directions = models.TextField(null=True)
    source = models.CharField(max_length=1000, null=True, blank=True)
    servings = models.IntegerField(default=0)
    prep_time = models.IntegerField(default=0)
    cook_time = models.IntegerField(default=0)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE,)
    publish_date = models.DateTimeField(default=timezone.now)
    edit_date = models.DateTimeField(default=timezone.now)
    pinned = models.BooleanField(default=False)
    banner_image = models.CharField(max_length=1000, null=True, blank=True)
    dish_type = models.IntegerField(choices=DISH_TYPE_CHOICES, default=0)
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag)

    # rating = RatingField(range=5)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )


class Ingredient(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,)
    name = models.CharField(max_length=80, null=False)
    comment = models.CharField(max_length=80, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=3, default=0.0)
    unit = models.CharField(max_length=30, null=True, blank=True)
    sorting = models.IntegerField("Ordering", blank=False, null=False, help_text="A number.")

    def __str__(self):
        return str(self.unit) + " " + str(self.name)

    class Meta:
        ordering = ('recipe_id', 'sorting', 'id', )
        unique_together = ('name', 'recipe', 'amount', 'unit',)
        select_on_save = True


class ShoppingList(models.Model):
    shoppingListId = models.AutoField(primary_key=True)
    ingredient = models.ForeignKey(Ingredient, blank=False, on_delete=models.CASCADE,)
    name = models.CharField(max_length=80, null=False)
    amount = models.IntegerField(default=0, null=True, blank=True)
    completed = models.BooleanField(default=False) # change to completed

    def __str__(self):
        return str(self.ingredient_id) + " " + str(self.status) + " " + str(self.amount)

    class Meta:
        ordering = ('completed', 'name', 'shoppingListId')


class IngredientMaster(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)

    def __str__(self):
        return str(self.id) + str(self.name)

    class Meta:
        ordering = ('name', 'id')


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,)
    comment = models.TextField(null=False)
    rating = models.IntegerField(null=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE,)
    publishDate = models.DateTimeField(default=timezone.now)
    editDate = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id) + str(self.comment)

    class Meta:
        ordering = ('-publishDate', '-id')


class PurchaseHistory(models.Model):
    id = models.AutoField(primary_key=True)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE,)
    purchaseAmount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, null=True, blank=True)
    purchaseUnit = models.CharField(max_length=30, null=True)
    store = models.CharField(max_length=30)
    lastPurchaseDate = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.id) + str(self.purchaseAmount) + str(self.price/self.purchaseAmount)

    class Meta:
        ordering = ('ingredient__name', 'id')


class Fridge(models.Model):
    id = models.AutoField(primary_key=True)
    item = models.CharField(max_length=80, unique=True, null=False)
    fridgedate = models.DateField(default=timezone.now)
    expires = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.recipe) + " " + str(self.fridgedate)

    class Meta:
        ordering = ('fridgedate', 'id')


class Rating(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,)
    rating = models.IntegerField(null=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE,)
    publishDate = models.DateTimeField(default=timezone.now)
    editDate = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id) + str(self.comment)

    class Meta:
        ordering = ('-publishDate', '-id')
        unique_together = ('recipe', 'user', )

menu/views.py
from django.shortcuts import get_object_or_404, render_to_response, render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.template import RequestContext
import csv
from datetime import datetime
from django.forms.models import modelformset_factory
import logging
import json
import sys
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test

from menu.forms import *
from .models import Recipe, Ingredient, Tag, ShoppingList, Fridge, Comment

def index(request):
    return HttpResponseRedirect(reverse('discover'))


def discover(request):

    search_form = SearchForm()

    if request.method == 'POST':
        search_form = SearchForm(request.POST)

        if search_form.is_valid():
            search_term = search_form.cleaned_data['search_term']

            recipes = Recipe.objects.filter(name__icontains=search_term)
            messages.info(request, search_term)
        else:
            recipes = Recipe.objects.filter(pinned='True')
    else:
        recipes = Recipe.objects.filter(pinned='True')

    return render(
        request,
        'discover.html',
        {
            'recipes': recipes,
            'search_form': search_form,
        },
    )


def add_to_shopping_list(request):
    ingredient_id = request.POST.get('ingredient_id')
    response_data = {}

    ingredient = Ingredient.objects.get(id=ingredient_id)
    list_item, created = ShoppingList.objects.get_or_create(ingredient_id=ingredient_id)

    list_item.amount = ingredient.amount
    list_item.name = ingredient.name
    list_item.ingredient = ingredient
    list_item.completed = False
    list_item.save()

    response_data['status'] = 'success'
    response_data['id'] = ingredient_id
    return JsonResponse(response_data)


def add_tag(request):
    recipe_id = request.POST.get('recipe_id')
    recipe = Recipe.objects.get(id=recipe_id)

    tag, created = recipe.tags.get_or_create(name=request.POST.get('name'))
    recipe.save()

    tags = ""
    for tag in recipe.tags.all():
        tags += " " + str(tag)

    response_data = {}
    response_data['status'] = 'success'
    response_data['tags'] = tags
    return JsonResponse(response_data)


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def shopping_list(request):
    shopping_list_entries = ShoppingList.objects.all()

    return render(
        request,
        'shopping_list.html',
        {'shopping_list_entries': shopping_list_entries, }
    )


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def shopping_list_check_off(request, shopping_list_id):

    shopping_list_entry = ShoppingList.objects.get(shoppingListId=shopping_list_id)
    shopping_list_entry.completed = True
    shopping_list_entry.save()

    return HttpResponseRedirect(reverse('shopping_list'))


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def shopping_list_delete(request, shopping_list_id):
    ShoppingList.objects.filter(shoppingListId=shopping_list_id).delete()

    return HttpResponseRedirect(reverse('shopping_list'))


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)

        if form.is_valid():
            formpost = form.save(commit=False)
            formpost.user = request.user
            formpost.edited = datetime.now()
            formpost.save()
            recipe_id = formpost.id
            messages.info(request, 'Recipe successfully added.')
            return HttpResponseRedirect(reverse('recipe_details', args=(recipe_id,)))
        else:
            messages.error(request, 'Please fill out all fields.')

    else:
        form = RecipeForm()

    return render(
        request,
        'edit_recipe.html',
        {'form': form},
    )


def clear_messages(request):
    storage = messages.get_messages(request)
    storage.used = True


def is_valid_ingredient(ingredient):
    return True


def add_comment_to_recipe(request):
    commentPost = request.POST
    comment_form = CommentForm(commentPost)
    recipe = Recipe.objects.get(pk=commentPost['recipe_id'])
    user = request.user
    if comment_form.is_valid():
        comment_save = comment_form.save(commit=False)
        comment_save.user = user
        comment_save.editDate = datetime.now()
        comment_save.recipe = recipe
        comment_save.save()
        response_data = {}
        response_data['status'] = 'success'
        response_data['comment'] = commentPost
        response_data['id'] = comment_save.id
        response_data['publishDate'] = comment_save.publishDate
        return JsonResponse(response_data)
    else:
        messages.error(request, 'Comment is required.')


def add_ingredient_to_recipe(request):
    ingredientPost = request.POST
    recipe = Recipe.objects.get(pk=ingredientPost['recipe_id'])
    ingredientForm = IngredientForm(ingredientPost)
    ingredients = Ingredient.objects.filter(recipe_id=recipe)
    clear_messages(request)

    if ingredientForm.is_valid():
        ingredient_save = ingredientForm.save(commit=False)
        ingredient_save.recipe = recipe
        messages.info(request, 'Ingredient ' + ingredient_save.name + ' added.')

        if ingredients:
            max_ingredient_sorting = Ingredient.objects.filter(recipe_id=recipe).order_by('-sorting')[0]
            ingredient_save.sorting = max_ingredient_sorting.sorting + 10
        else:
            ingredient_save.sorting = 10

        ingredient_save.save()
        response_data = {}
        response_data['status'] = 'success'
        response_data['ingredient'] = ingredientPost
        response_data['id'] = ingredient_save.id
        return JsonResponse(response_data)
    else:
        messages.error(request, 'Ingredient name and amount are required.')


def recipe_details(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)
    user = request.user
    tag_form = TagForm()
    comment_form = CommentForm()
    ingredient_form = IngredientForm()
    return render(
        request,
        'recipe_details.html',
        {
            'tag_form': tag_form,
            'comment_form': comment_form,
            'ingredient_form': ingredient_form,
            'recipe': recipe,
        },
    )


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def delete_recipe_forever(request, recipe_id):
    Recipe.objects.filter(pk=recipe_id).delete()
    return HttpResponseRedirect(reverse('my_recipes'))


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def edit_recipe(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)
    ingredients = Ingredient.objects.filter(recipe_id=recipe)
    ingredient_form = IngredientForm()
    recipe_form = RecipeForm(instance=recipe)

    if request.method == 'POST':
        recipe_form = RecipeForm(request.POST, instance=Recipe.objects.get(id=recipe_id))

        if recipe_form.is_valid():
            recipe_save = recipe_form.save(commit=False)
            recipe_save.user = request.user
            recipe_save.edited = datetime.now()
            recipe_save.save()
            recipe_id = recipe_save.id
            messages.info(request, 'Recipe successfully updated.')
            return HttpResponseRedirect(reverse('recipe_details', args=(recipe_id,)))

    return render(
        request,
        'edit_recipe.html',
        {
            'form': recipe_form,
            'recipe': recipe,
        },
    )


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def edit_ingredient(request, ingredient_id):

    ingredient = Ingredient.objects.get(id=ingredient_id)
    recipe = Recipe.objects.get(id=ingredient.recipe_id)

    if request.method == 'POST':
        ingredient_form = IngredientForm(request.POST, instance=Ingredient.objects.get(id=ingredient_id))

        if ingredient_form.is_valid():
            formpost = ingredient_form.save(commit=False)
            formpost.user = request.user
            formpost.edited = datetime.now()
            formpost.save()
            return HttpResponseRedirect(reverse('edit_recipe', args=(recipe.id,)))

    else:
        ingredient_form = IngredientForm(instance=ingredient)

        return render(
            request,
            'edit_ingredient.html',
            {
                'ingredient_form': ingredient_form,
                'recipe': recipe,
                'ingredient': ingredient
            },
        )


@user_passes_test(lambda u: u.is_superuser, login_url='not_authorized')
def delete_ingredient(request, ingredient_id):
    i = Ingredient.objects.get(pk=ingredient_id)
    Ingredient.objects.filter(pk=ingredient_id).delete()
    return HttpResponseRedirect(reverse('recipe_details', args=(i.recipe_id,)) + '#ingredients')


@login_required()
def comment_delete(request, comment_id):
    c = Comment.objects.get(pk=comment_id)
    Comment.objects.filter(pk=comment_id).delete()
    return HttpResponseRedirect(reverse('recipe_details', args=(c.recipe_id,)) + '#comments')


class FauxTb(object):
    def __init__(self, tb_frame, tb_lineno, tb_next):
        self.tb_frame = tb_frame
        self.tb_lineno = tb_lineno
        self.tb_next = tb_next


def current_stack(skip=0):
    try:
        1 / 0
    except ZeroDivisionError:
        f = sys.exc_info()[2].tb_frame
    for i in xrange(skip + 2):
        f = f.f_back
    lst = []
    while f is not None:
        lst.append((f, f.f_lineno))
        f = f.f_back
    return lst


def extend_traceback(tb, stack):
    """Extend traceback with stack info."""
    head = tb
    for tb_frame, tb_lineno in stack:
        head = FauxTb(tb_frame, tb_lineno, head)
    return head


def full_exc_info():
    """Like sys.exc_info, but includes the full traceback."""
    t, v, tb = sys.exc_info()
    full_tb = extend_traceback(tb, current_stack(1))

menu/templates/add_comment.html
{% load staticfiles %}
{% load menu_extras %}
<div class="wrapper">
  <div id="addCommentModal" class="modal">
    <div class="modal-container modal-toast">
        <div class="form-container-wrapper">
          <form class="form-container" method="POST" action="">
            {% csrf_token %}
            {{ comment_form }}
            <div class="submit-container">
              <a id="cancel-comment-add" class="submit-button">Cancel</a>                
              <a class="submit-button" id="{{ recipe.id }}" onClick="add_comment_to_recipe(this.id)">Save</a>
            </div>
            <div style="clear:both;"></div>
          </form>
        </div>
      <div style="clear:both;"></div>
    </div>
  </div>
</div>

menu/templates/discover.html
{% extends "base.html" %}
{% load staticfiles %}
{% load menu_extras %}
{% load markdown_deux_tags %}

<html>
<body>
{% block title %}
{% endblock %}
{% block content %}
<h3>Discover Recipes</h3>

<form action="" method="POST" class="search_form">
  {% csrf_token %}
  {{ search_form }}
  <a class="btn" href="{% url 'clear_recipe_filter' %}">&#x2718;
  {% for message in messages %}
    {% if message.tags == 'info' %}
      {{ message }}
    {% endif %}
  {% endfor %}
  </a>
</form>

<div style="clear:both;"></div>

<div class="hero-unit">
</div>

<div class="new_post_block" onclick="location.href='{% url 'add_recipe' %}'">
  <div class="fixed-action-btn" style="bottom: 24px; right: 24px;">
    <a class="btn-floating red">
      <f class="large material-icons">+</f>
    </a>
  </div>
</div>

{% for recipe in recipes %}
  <div class="recipe_block notSelectable" id="{{ recipe.id }}">
    <span class="recipe_title"><a href="{% url 'recipe_details' recipe.id %}">{{ recipe.name }}</a></span>
    <img src="{% static recipe.get_dish_type_display|generate_img_path %}" height="10em">
  </div>
{% endfor %}

{% endblock %}
</body>
</html>

menu/templates/edit_recipe.html
{% extends "base.html" %}
{% load staticfiles %}
{% load menu_extras %}
<html>
<head>
<title>
  {% block head_title %}
    {% if recipe.name %}
      {{ recipe.name }} - Edit
    {% else %}
      New Recipe
    {% endif %}
  {% endblock %}
</title>
</head>
<body>
{% block content %}

{% for message in messages %}
  {% if message.tags == 'error' %}
    <p style="color:red; font-weight:bold;">{{ message }}</p>
  {% elif message.tags == 'info' %}
    <p style="color:black; font-weight:bold;">{{ message }}</p>
  {% endif %}
{% endfor %}

{% if recipe.name %}
  <div class="hero-unit"><h2>Edit Ingredients</h2></div>
  <div class="ingredients">
  {% for ingredient in recipe.ingredient_set.all %}
    <div class="ingredient_block">
      <div class="ingredient_details">
        {{ ingredient.amount|show_integer }}{{ ingredient.amount|show_fraction }}
        {{ ingredient.unit }}
        {{ ingredient.name }}{% if ingredient.comment %}, {{ ingredient.comment }}
        {% endif %}
        <a class="right_tab_button" href="{% url 'edit_ingredient' ingredient.id %}">
          <img style="margin-top: 5px;" src="{% static 'edit_recipe_icon'|generate_img_path %}" height="12em">
        </a>
        <a class="right_tab_button" href="{% url 'move_ingredient_up' ingredient.id %}">
          <img style="margin-top: 5px;" src="{% static 'chevron_sign_up'|generate_img_path %}" height="12em">
        </a>
        <a class="right_tab_button" href="{% url 'move_ingredient_down' ingredient.id %}">
          <img style="margin-top: 5px;" src="{% static 'chevron_sign_down'|generate_img_path %}" height="12em">
        </a>
      </div>
    </div>
  {% endfor %}
  </div>
  <div style="clear:both;"></div>
{% else %}
  <div class="hero-unit"><h1>New Recipe</h1></div>
{% endif %}
<hr>

<div class="form-container-wrapper">
  <form class="form-container" method="POST" action="" name="recipe_form">
    <div class="form-title"><h2>Edit Recipe Details</h2></div>
    {% csrf_token %}
    {{ form.name.label }}<br>{{ form.name }}<br>
    {{ form.description.label }}<br>{{ form.description }}<br>
    {{ form.cook_method.label }}<br>{{ form.cook_method }}<br>
    {{ form.dish_type.label }}<br>{{ form.dish_type }}<br>
    {{ form.temperature.label }}<br>{{ form.temperature }}<br>
    {{ form.prep_time.label }}<br>{{ form.prep_time }}<br>
    {{ form.cook_time.label }}<br>{{ form.cook_time }}<br>
    {{ form.servings.label }}<br>{{ form.servings }}<br>
    {{ form.directions.label }}<br>{{ form.directions }}<br>
    {{ form.source.label }}<br>{{ form.source }}<br>
    <div class="submit-container">
      {% if recipe.id != null %}
        <a class="submit-button" href="{% url 'recipe_details' recipe.id %}">Cancel</a>
      {% else %}
        <a class="submit-button" href="{% url 'my_recipes' %}">Cancel</a>
      {% endif %}
      <input class="submit-button" type="submit" value="Update &raquo;"/>
    </div>
  </form>
</div>

{% endblock %}
</body>

<script type="text/javascript" src="{% static 'menu/js/jquery-1.11.3.js' %}"></script>
<script type="text/javascript" src="{% static 'menu/js/menu.js' %}"></script>

</html>

menu/templates/my_recipes.html
{% extends "base.html" %}
{% load staticfiles %}
{% load menu_extras %}
{% load markdown_deux_tags %}

{% block content %}
{% if user.is_superuser %}

<h3>Your Recipes</h3>
{% for recipe in recipes %}
<div class="recipe_block" id="{{ recipe.id }}">
  <span class="recipe_title"><a href="{% url 'recipe_details' recipe.id %}">{{ recipe.name }}</a></span>
  <img src="{% static recipe.get_dish_type_display|generate_img_path %}" height="10em">
</div>
{% endfor %}
{% endif %}
{% endblock %}

menu/templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load menu_extras %}
{% load markdown_deux_tags %}

{% block content %}
{% if user.is_superuser %}

<h3>Your Recipes</h3>
{% for recipe in recipes %}
<div class="recipe_block" id="{{ recipe.id }}">
  <span class="recipe_title"><a href="{% url 'recipe_details' recipe.id %}">{{ recipe.name }}</a></span>
  <img src="{% static recipe.get_dish_type_display|generate_img_path %}" height="10em">
</div>
{% endfor %}
{% endblock %}

menu/templates/recipe_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% load menu_extras %}
{% load markdown_deux_tags %}

{% block head_title %}
  {{ recipe.name }} - Details
{% endblock %}
{% block content %}

<!-- ADD INGREDIENT MODAL-->
{% include "add_ingredient.html" %}    
<!-- ADD TAG MODAL-->
{% include "add_tag.html" %}

<div class="hero-unit">
  <h1>{{ recipe.name }}</h1>
</div>

<!-- ACTION BUTTONS -->
{% if user.is_superuser %}

<div id="footer">
  <div id="add-tag-button" class="pink button">
    Tag
  </div>
  <div id="add-note-button" class="orange button">
    Note
  </div>
  <div id="add-ingredient-button" class="green button">
    Ingredient
  </div>
  <div class="blue button" onclick="location.href='{% url 'edit_recipe' recipe.id %}'">
    Edit
  </div>
</div>
{% endif %}

<div class="recipe_header gray_background">
  <div class="recipe_description">
    {% if recipe.description|length > 0 %}
      {% markdown %}
        {{ recipe.description }}
      {% endmarkdown %}
    {% endif %}
  </div>

  <div class="recipe_info">
    <ul>
      <li><b>Cook Method</b>: {{ recipe.get_cook_method_display }}</li>
      <li><b>Dish Type</b>: {{ recipe.get_dish_type_display }}</li>
      <li><b>Temp</b>: {{ recipe.temperature }}</li>
      <li><b>Prep Time</b>:
        {% if recipe.prep_time < 60 %}
          {{ recipe.prep_time }} minute(s)</li>
        {% else %}
          {{ recipe.prep_time|minutes_to_hours|floatformat:"1" }} hour(s)
        {% endif %}
      <li><b>Cook Time</b>:
        {% if recipe.cook_time < 60 %}
          {{ recipe.cook_time }} minute(s)
        {% else %}
          {{ recipe.cook_time|minutes_to_hours|floatformat:"1" }} hour(s)
        {% endif %}
      </li>
      <li><b>Servings</b>: {{ recipe.servings }}</li>
      {% if user.is_superuser %}
        <li><a class="" target="_blank" href="{{ recipe.source }}">GoTo Recipe Source</a></li>
      {% endif %}
      <li><b>Tags</b>:
        <span id="tagsSection">
          {% for tag in recipe.tags.all %}
            {{ tag }}
          {% empty %}
            no tags
          {% endfor %}
        </span>
      </li>
    </ul>
  </div>
  <div style="clear:both;"></div>
</div>

<div id="ingredients_section">
  {% include "recipe_details_ingredients.html" %}
  <div style="clear:both;"></div>
</div>
<hr>

<div class="recipe_directions">
  <div class="hero-unit">
    <h2>Directions</h2>
  </div>
  {% markdown %}
    {{ recipe.directions | safe }}
  {% endmarkdown %}
</div>
<hr>
<div class="recipe_notes">
  <!-- ADD COMMENT MODAL-->
  {% include "add_comment.html" %}
  <div class="hero-unit">
    <h2>Notes</h2>
  </div>
  {% if recipe.comment_set.all %}
    <div id="comments_section">
      {% for comment in recipe.comment_set.all %}
        <div class="comment_block notSelectable" id="{{ comment.recipe.id }}">
          {{ comment.publishDate }}
          {% if user.is_superuser %}
            <a href="{% url 'comment_delete' comment.id %}"
              onclick="return confirm('Are you sure you want to delete this note?')">
              <img style="margin-top: 5px;" src="{% static 'delete_icon'|generate_img_path %}" height="16em">
            </a>
          {% endif %}
          <br>
          {{ comment.comment}}
        </div>
        <hr>
      {% endfor %}
    </div>
  {% endif %}
</div>

{% endblock %}

menu/templates/shopping_history.html
{% extends "base.html" %}
{% load staticfiles %}
{% load menu_extras %}

<html>
  <body>
    {% block title %}
      <div id="title">
        Shopping List History
      </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block navsidebar %}
    {% endblock %}
  </body>
</html>